name: Daily Auto-Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: debeshee05@gmail.com
        run: |
          git config --global user.email "debeshee05@gmail.com"
          git config --global user.name "DebesheeSen"
          git add .
          git commit -m "Update"
          git push origin main
