name: Daily Auto-Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: debeshee05@gmail.com
        run: |
          git config --global user.email "debeshee05@gmail.com"
          git config --global user.name "DebesheeSen"
          git add .
          git commit -m "Update once per day"
          git push
